### ISSUE TITLE
cargo install fails: mismatched types

### ISSUE THREAD

**Issue by yglukhov** [paritytech/wasm-utils#92] opened 2018-07-03 17:56 UTC
The command from the readme:
```
cargo install pwasm-utils-cli --bin wasm-gas
```
<details> 
<summary>Fails with error:</summary>
<pre>
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing pwasm-utils-cli v0.1.0
   Compiling void v1.0.2
   Compiling libc v0.2.42
   Compiling regex v1.0.1
   Compiling lazy_static v1.0.1
   Compiling ucd-util v0.1.1
   Compiling quick-error v1.2.2
   Compiling cfg-if v0.1.4
   Compiling byteorder v1.2.3
   Compiling unicode-width v0.1.5
   Compiling utf8-ranges v1.0.0
   Compiling strsim v0.7.0
   Compiling vec_map v0.8.1
   Compiling termcolor v0.3.6
   Compiling bitflags v1.0.3
   Compiling ansi_term v0.11.0
   Compiling glob v0.2.11
   Compiling unreachable v1.0.0
   Compiling humantime v1.1.1
   Compiling log v0.4.3
   Compiling regex-syntax v0.6.1
   Compiling memchr v2.0.1
   Compiling atty v0.2.10
   Compiling textwrap v0.10.0
   Compiling parity-wasm v0.31.0
   Compiling parity-wasm v0.30.0
   Compiling thread_local v0.3.5
   Compiling aho-corasick v0.6.5
   Compiling clap v2.32.0
   Compiling pwasm-utils v0.2.2
   Compiling env_logger v0.5.10
   Compiling pwasm-utils-cli v0.1.0
error[E0308]: mismatched types
  --> gas/main.rs:20:3
   |
20 |         module, &Default::default()
   |         ^^^^^^ expected struct `parity_wasm::elements::module::Module`, found struct `parity_wasm::elements::Module`
   |
   = note: expected type `parity_wasm::elements::module::Module`
              found type `parity_wasm::elements::Module`
note: Perhaps two different versions of crate `parity_wasm` are being used?
  --> gas/main.rs:20:3
   |
20 |         module, &Default::default()
   |         ^^^^^^

error[E0308]: mismatched types
  --> gas/main.rs:23:43
   |
23 |     parity_wasm::serialize_to_file(&args[2], result).expect("Module serialization to succeed")
   |                                              ^^^^^^ expected struct `parity_wasm::elements::Module`, found struct `parity_wasm::elements::module::Module`
   |
   = note: expected type `parity_wasm::elements::Module`
              found type `parity_wasm::elements::module::Module`
note: Perhaps two different versions of crate `parity_wasm` are being used?
  --> gas/main.rs:23:43
   |
23 |     parity_wasm::serialize_to_file(&args[2], result).expect("Module serialization to succeed")
   |                                              ^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: failed to compile `pwasm-utils-cli v0.1.0`, intermediate artifacts can be found at `/var/folders/64/sn9g0cy15gj55lmm0rcxymcm0000gn/T/cargo-installqtpItd`

Caused by:
  Could not compile `pwasm-utils-cli`.

To learn more, run the command again with --verbose.
</pre>
</details>

**Comment by fckt** [comment] 2018-07-03 21:29
```
   Compiling parity-wasm v0.31.0
   Compiling parity-wasm v0.30.0
```

The issue is that two versions of parity-wasm are linking at the same time.. Seems like Cargo.lock is not in sync

**Comment by NikVolf** [comment] 2018-07-04 09:15
> Seems like Cargo.lock is not in sync

what Cargo.lock ?

**Comment by NikVolf** [comment] 2018-07-04 09:20
I think this is collateral damage of https://github.com/paritytech/wasm-utils/pull/91

version should have been bumped to 0.3 and 0.2 for cli

fixed now

**Closed by NikVolf** 2018-07-04 09:20 UTC
